### ISSUE TITLE
URL escaping

### ISSUE THREAD

**Issue by palkan** [imgproxy/imgproxy.rb#48]
URL escaping is not happening when using `s3://` urls:

```ruby
Imgproxy.url_for("s3://bucket/file") #=> "https://img.proxy.com/<key>/plain/s3://bucket/file"
```

See also https://github.com/aws/aws-sdk-ruby/pull/2300

**Comment by mullermp** [comment]
This is where a change is probably needed: https://github.com/imgproxy/imgproxy.rb/blob/master/lib/imgproxy/url_adapters/shrine_s3.rb#L17

**Comment by mullermp** [comment]
Changes might be needed in these two locations:

https://github.com/imgproxy/imgproxy.rb/blob/master/lib/imgproxy/url_adapters/shrine_s3.rb#L17
https://github.com/imgproxy/imgproxy.rb/blob/master/lib/imgproxy/url_adapters/active_storage_s3.rb#L19

Though I'm not sure what happens if these are changed without other changes on the image proxy service side..

**Comment by mullermp** [comment]
@DarthSim do you mind investigating? :)

**Comment by DarthSim** [comment]
Hey,

I'm very sorry for so long delay.

From imgproxy's point of view `s3://` URLs don't need to be escaped. However, I see that, in some cases, force escaping may be useful. I added `always_escape_plain_urls` config and `escape_plain_url` option to master. I hope this helps.

**Comment by mullermp** [comment]
@DarthSim Thanks!

I merged a change on our end regardless, but this should unblock @palkan
